
target-y = \
	creator \
	fixedpoint

fixedpoint_common_files = \
	r128.h \
	fixedpoint.c \

fixedpoint_files-y = \
	${fixedpoint_common_files}

fixedpoint_includes-y = \

fixedpoint_cflags-y += \

config_common_files = \
	r128.h \
	config.c \

config_files-y = \
	${config_common_files}

config_includes-y = \

config_cflags-y += \

creator_common_files = r128.h creator.c
creator_files-y = ${creator_common_files}
creator_includes-y = \
creator_cflags-y += \

# tests
#subdir-y += \
#	test

#test_depends-y = \
#	lib*.a

include ../Makefile.lib
