
target-y = \
	creator \
	fixedpoint

creator_common_files = creator.c macros.h r128.h
creator_files-y = ${creator_common_files}
creator_includes-y = \
creator_cflags-y += \

fixedpoint_common_files = fixedpoint.c macros.h r128.h
fixedpoint_files-y = ${fixedpoint_common_files}
fixedpoint_includes-y = \
fixedpoint_cflags-y += \

# tests
#subdir-y += \
#	test

#test_depends-y = \
#	lib*.a

include ../Makefile.lib
