
target-y = \
	fixedpoint

fixedpoint_common_files = \
	r128.h \
	fixedpoint.c \

fixedpoint_files-y = \
	${fixedpoint_common_files}

fixedpoint_includes-y = \

fixedpoint_cflags-y += \

# tests
#subdir-y += \
#	test

#test_depends-y = \
#	lib*.a

include ../Makefile.lib
